from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
TEMPLATE = PAPER / "ReproducibilityChecklist.tex"
OUTPUT = PAPER / "ReproducibilityChecklist_HARP_GNN.tex"


ANSWERS = [
    "partial. The Method section gives equations for the low-pass branch, high-pass residual branch, and node-adaptive gate; explicit pseudocode is not yet included.",
    "yes. Hypotheses and bounded evidence are separated from measured results in the abstract, result discussion, and limitations.",
    "yes. The related-work section cites standard GNN, heterophily, polynomial-filter, and benchmark references.",
    "no. The paper proposes an empirical architecture and does not make formal theoretical contributions.",
    "NA",
    "NA",
    "NA",
    "NA",
    "NA",
    "NA",
    "NA",
    "yes",
    "partial. The Experiments section motivates synthetic homophily stress tests, Planetoid checks, WebKB, and larger Geom-GCN heterophily benchmarks.",
    "NA. The paper does not introduce a new fixed dataset.",
    "NA. The paper does not introduce a new fixed dataset.",
    "yes. Existing datasets are cited in the manuscript bibliography.",
    "yes. The reported datasets are public and loaded through repository dataset loaders.",
    "NA. The paper does not rely on non-public datasets.",
    "yes",
    "partial. Final settings and selection by validation accuracy are specified in configs; the full development search range is not yet exhaustively documented in the manuscript.",
    "partial. Dataset loading and preprocessing code are included in the repository, but not as a separate paper appendix.",
    "yes. The repository contains experiment, model, data-loading, summarization, audit, and verification code.",
    "partial. The code is prepared for release, but the final public license should be selected before publication.",
    "partial. Core model code is documented with class docstrings and clear names; line-by-line links back to paper equations are not yet complete.",
    "yes. Seeds are specified in each YAML config and set through the shared set\\_seed utility.",
    "partial. The repository records software requirements and local CPU/Windows context; exact CPU model, memory, and library versions should be frozen before final submission.",
    "partial. Accuracy, standard deviation, and paired tests are described; metric motivation can be expanded in the manuscript.",
    "yes. Tables and configs state the number of seeds or fixed splits used for each reported benchmark.",
    "yes. Reported tables include standard deviations and paired-split statistical tests where applicable.",
    "partial. Paired t-tests are reported for WebKB and larger Geom-GCN; not every diagnostic table has a statistical test.",
    "partial. Final hyperparameters are in YAML configs; a compact manuscript or supplementary hyperparameter table should be added before final submission.",
]


def main() -> None:
    text = TEMPLATE.read_text(encoding="utf-8")
    marker = "% The questions start here"
    if marker not in text:
        raise SystemExit(f"Could not find checklist question marker: {marker}")

    prefix, questions = text.split(marker, 1)
    question_block = marker + questions
    expected = question_block.count("Type your response here")
    if expected != len(ANSWERS):
        raise SystemExit(f"Expected {expected} answers from template, but have {len(ANSWERS)}.")

    for answer in ANSWERS:
        question_block = question_block.replace("Type your response here", answer, 1)

    header = "% Filled HARP-GNN reproducibility checklist generated by scripts/fill_reproducibility_checklist.py.\n"
    OUTPUT.write_text(header + prefix + question_block, encoding="utf-8")
    print(f"[saved] {OUTPUT}")


if __name__ == "__main__":
    main()
